eventcodedict = {1: 'Servo 1 open',
                3: 'Servo 2 open',
                5: 'Servo 3 open',
                7: 'Servo 4 open',
                9: 'Mouse in hall 1',
                10: 'Mouse in offer zone 1',
                11: 'Enter R1',
                12: 'Reject R1',
                13: 'Quit R1',
                15: 'R1 no-reward tone',
                16: 'R1 reward taken',
                17: 'R1 0% offer',
                18: 'R1 20% offer',
                19: 'R1 80% offer',
                20: 'R1 100% offer',
                21: 'Mouse in hall 2',
                22: 'Mouse in offer zone 2',
                23: 'Enter R2',
                24: 'Reject R2',
                25: 'Quit R2',
                27: 'R 2 no-reward tone',
                28: 'R2 reward taken',
                29: 'R 2 0% offer',
                30: 'R2 20% offer',
                31: 'R2 80% offer',
                32: 'R2 100% offer',
                33: 'Mouse in hall 3',
                34: 'Mouse in offer zone 3',
                35: 'Enter R3',
                36: 'Reject R3',
                37: 'Quit R3',
                39: 'R3 no-reward tone',
                40: 'R3 reward taken',
                41: 'R3 0% offer',
                42: 'R3 20% offer',
                43: 'R3 80% offer',
                44: 'R3 100% offer',
                45: 'Mouse in hall 4',
                46: 'Mouse in offer zone 4',
                47: 'Enter R4',
                48: 'Reject R4',
                49: 'Quit R4',
                51: 'R4 no-reward tone',
                52: 'R4 reward taken',
                53: 'R4 0% offer',
                54: 'R4 20% offer',
                55: 'R4 80% offer',
                56: 'R4 100% offer',
                61: 'SHARP Entry R1',
                64: 'SHARP Entry R2',
                67: 'SHARP Entry R3',
                70: 'SHARP Entry R4'}
